apiVersion: v1
kind: Service
metadata:
  name: mongo-wallet
  labels:
    app: mongo-wallet
spec:
  type: ClusterIP
  selector:
    app: mongo-wallet
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 8080
